#spring:
#  application:
#    name: room-service
#  data:
#    mongodb:
#     uri: mongodb://localhost:27017/room
#  com.piseth.java.school: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb+srv://mongovibol:hello123@cluster-1-roomservice.20qx8qp.mongodb.net/Enterprice?retryWrites=true&w=majority
logging:
 level:
  root: INFO