server:
 port: 8080

spring:
  application:
    name: room-service    
  data:
    mongodb:
      host: 10.172.9.189
      port: 27018
      database: roomService
      username: root
      password: root
      authentication-database: admin
  kafka:
    bootstrap-servers: 10.172.9.189:9092
    consumer:
      #group-id: visitor-room-projection
      group-id: visitor-room-projection-3
      auto-offset-reset: earliest # (start from beginning)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.piseth.java.school.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.piseth.java.school.roomservice.message.event.RoomEventEnvelope
      max-poll-records: 100        
logging:
  level:
    root: INFO
    com.piseth.java.school: DEBUG   

app:
  messaging:
    topics:
      roomEvents: room.events.v1

storage:
    publicBaseUrl: http://10.172.9.189:9000