version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: admin-areas-mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

volumes:
  mongodb_data: